# Generated by Django 4.2.5 on 2023-09-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidora', '0002_alter_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos-img/'),
        ),
    ]
